name: Backend CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Setup SSH key
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          env
          mkdir -p ~/.ssh
          echo "${SSH_KEY}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 ${SSH_HOST} >> ~/.ssh/known_hosts

      - name: Prepare target directory permissions
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
            ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} << 'EOF'
            sudo mkdir -p /var/www/html/backend
            sudo chown -R $USER:devs /var/www/html/backend
            sudo chmod -R 775 /var/www/html/backend
            EOF

      - name: Deploy
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          rsync -avz --delete --exclude-from='.github/workflows/backend-rysnc-exclude.txt' -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" \
            backend/ ${SSH_USERNAME}@${SSH_HOST}:/var/www/html/backend/

          ssh ${SSH_USERNAME}@${SSH_HOST} << 'EOF'
          cd /var/www/html/backend
          npm ci

          if pm2 describe server > /dev/null; then
            echo "PM2 Exists: Restarting"
            pm2 restart server
          else
            echo "PM2 doesn't exist: Starting"
            pm2 start server.js --name backend
          fi

          pm2 save

          EOF
